---
- hosts: 172.31.13.243 
  become: yes 
  tasks: 
  - name: execute linux command by using playbook 
    command: hostname -f 
    register: myfirsttaskresult


  - name: i want to dabug first task result
    debug: 
       msg: "{{myfirsttaskresult}}" 