---
- hosts: 172.31.13.243 
  become: yes 
  tasks: 
  - name: execute linux command by using playbook 
    command: hostname -f 
    register: myfirsttaskresult


  - name: i want to dabug first task result
    debug: 
       msg: "{{myfirsttaskresult}}" 

  - name: install git 
    apt: 
       name: git 
       state: present 
    when: myfirsttaskresult.stderr=""
  - name: install tree 
    apt: 
      name: tree 
      state: present

    when: myfirsttaskresult.stderr=""